name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: msrd0
          token: ${{secrets.METRICS_TOKEN}}
          committer_token: ${{secrets.GITHUB_TOKEN}}

          repositories_skipped: msrd0/docs

          config_timezone: Europe/Amsterdam

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 6

          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: no

          extras_css: |
            @media (prefers-color-scheme: dark) {
              h1, h2, h3 {
                color: #284a92 !important;
              }
            }
          extras_js: |
            for (const {a, b} of [
              {a:"#216e39", b:1},
              {a:"#30a14e", b:0.8},
              {a:"#40c463", b:0.6},
              {a:"#9be9a8", b:0.4},
              {a:"#ebedf0", b:0.2},
            ]) {
              document.querySelectorAll(`svg g [fill="${a}"]`)
                .forEach(node => node.setAttribute("fill", `hsl(120deg 100% 45% / ${b})`));
            }
