name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: msrd0
          token: ${{secrets.METRICS_TOKEN}}
          committer_token: ${{secrets.GITHUB_TOKEN}}

          repositories_skipped: msrd0/docs

          config_timezone: Europe/Amsterdam

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 5

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
